=== PLOS/rhino/src/main/resources/manifest.dtd
<!--
 Copyright (c) 2006-2010 by Public Library of Science
 http://plos.org
 http://ambraproject.org
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!--
  - This is the DTD of the manifest. A submission information package (SIP) is a zip archive
  - with a manifest; the manifest is an entry called "manifest.xml" which must conform to
  - this DTD.
  -->

<!ELEMENT manifest (articleBundle) >

<!ELEMENT articleBundle (article, object*) >

<!-- the article. 'main-entry' specifies the zip entry that contains the nlm
   - article xml; this must match one of the contained representations
   -->
<!ELEMENT article (representation+) >
<!ATTLIST article
    uri         CDATA          #REQUIRED 
    main-entry  CDATA          #REQUIRED >

<!-- all included secondary objects (images, movies, data, etc) -->
<!ELEMENT object (representation+) >
<!ATTLIST object
    uri         CDATA          #REQUIRED 
    strkImage   CDATA          #IMPLIED          >

<!-- a specific representation.
   - 'name' is the name (label) to store this representation under;
   - 'entry' specifies the entry in the zip that contains this representation
   -->
<!ELEMENT representation EMPTY >
<!ATTLIST representation
    name        CDATA          #REQUIRED 
    entry       CDATA          #REQUIRED >



<!-- Example:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifest SYSTEM "manifest.dtd">
<manifest>
  <articleBundle>
    <article uri="info:doi/10.1371/journal.foo.00042" main-entry="my-article.xml">
      <representation name="XML" entry="my-article.xml"/>
      <representation name="PDF" entry="my-article.pdf"/>
    </article>
    <object uri="info:doi/10.1371/journal.foo.00042.g001" strkImage="True">
      <representation name="PNG_S" entry="image01.small.png"/>
      <representation name="PNG_L" entry="image01.large.png"/>
    </object>
    <object uri="info:doi/10.1371/journal.foo.00042.g002">
      <representation name="PNG_S" entry="image02.small.png"/>
      <representation name="TIFF"  entry="image02.tiff"/>
    </object>
  </articleBundle>
</manifest>
-->

=== PLOS/rhino/src/test/resources/org/ambraproject/rhino/service/impl/manifest.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE manifest SYSTEM "manifest.dtd">
<manifest>
	<articleBundle>
		<article uri="info:doi/10.1111/dupp.0000001">
			<representation entry="dupp.0000001.xml" key="10.1111/dupp.0000001.XML"
				mimetype="application/xml" type="manuscript" />
			<representation entry="dupp.0000001.pdf" key="10.1111/dupp.0000001.pdf"
				mimetype="application/pdf" type="printable" />
		</article>
		<object type="supplementaryMaterial" uri="info:doi/10.1111/dupp.0000001.s001" strkImage="true">
			<representation entry="dupp.0000001.s001.png" key="10.1111/dupp.0000001.s001.png"
				mimetype="image/ext" type="supplementary" />
		</object>
		<object type="supplementaryMaterial" uri="info:doi/10.1111/dupp.0000001.s002">
			<representation entry="dupp.0000001.s002.jpg" key="10.1111/dupp.0000001.s002.jpg"
				mimetype="image/ext" type="supplementary" />
		</object>
		<object type="supplementaryMaterial" uri="info:doi/10.1111/dupp.0000001.s003">
			<representation entry="dupp.0000001.s003.xlsx" key="10.1111/dupp.0000001.s003.xlsx"
				mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
				type="supplementary" />
		</object>
		<object type="supplementaryMaterial" uri="info:doi/10.1111/dupp.0000001.s004">
			<representation entry="dupp.0000001.s004.docx" key="10.1111/dupp.0000001.s004.docx"
				mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
				type="supplementary" />
		</object>
		<object type="supplementaryMaterial" uri="info:doi/10.1111/dupp.0000001.s005">
			<representation entry="dupp.0000001.s005.docx" key="10.1111/dupp.0000001.s005.docx"
				mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
				type="supplementary" />
		</object>
		<object type="supplementaryMaterial" uri="info:doi/10.1111/dupp.0000001.s006">
			<representation entry="dupp.0000001.s006.docx" key="10.1111/dupp.0000001.s006.docx"
				mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
				type="supplementary" />
		</object>
		<object type="supplementaryMaterial" uri="info:doi/10.1111/dupp.0000001.s007">
			<representation entry="dupp.0000001.s007.docx" key="10.1111/dupp.0000001.s007.docx"
				mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
				type="supplementary" />
		</object>
	</articleBundle>
	<ancillary>
		<file entry="manifest.xml" key="10.1111/dupp.0000001.manifest.xml"
			mimetype="application/xml" />
		<file entry="manifest.dtd" key="10.1111/dupp.0000001.manifest.dtd"
			mimetype="application/xml-dtd" />
	</ancillary>
</manifest>

=== PLOS/rhino/test/data/PrePrint/manifest.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE manifest SYSTEM "manifest.dtd">
<manifest>
 <articleBundle>
  <article uri="info:doi/10.24196/journal.aarx.2001421">
   <representation entry="aarx.2001421.xml" key="10.24196/journal.aarx.2001421.XML" mimetype="application/xml" type="manuscript"/>
   <representation entry="aarx.2001421.pdf" key="10.24196/journal.aarx.2001421.pdf" mimetype="application/pdf" type="printable"/>
  </article>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s001">
   <representation entry="aarx.2001421.s001.xlsx" key="10.24196/journal.aarx.2001421.s001.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s002">
   <representation entry="aarx.2001421.s002.tif" key="10.24196/journal.aarx.2001421.s002.tif" mimetype="image/tiff" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s003">
   <representation entry="aarx.2001421.s003.xlsx" key="10.24196/journal.aarx.2001421.s003.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s004">
   <representation entry="aarx.2001421.s004.tif" key="10.24196/journal.aarx.2001421.s004.tif" mimetype="image/tiff" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s005">
   <representation entry="aarx.2001421.s005.xlsx" key="10.24196/journal.aarx.2001421.s005.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s006">
   <representation entry="aarx.2001421.s006.xlsx" key="10.24196/journal.aarx.2001421.s006.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s007">
   <representation entry="aarx.2001421.s007.xlsx" key="10.24196/journal.aarx.2001421.s007.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s008">
   <representation entry="aarx.2001421.s008.xlsx" key="10.24196/journal.aarx.2001421.s008.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s009">
   <representation entry="aarx.2001421.s009.xlsx" key="10.24196/journal.aarx.2001421.s009.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s010">
   <representation entry="aarx.2001421.s010.xlsx" key="10.24196/journal.aarx.2001421.s010.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s011">
   <representation entry="aarx.2001421.s011.xlsx" key="10.24196/journal.aarx.2001421.s011.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s012">
   <representation entry="aarx.2001421.s012.jpg" key="10.24196/journal.aarx.2001421.s012.jpg" mimetype="image/jpeg" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s013">
   <representation entry="aarx.2001421.s013.xlsx" key="10.24196/journal.aarx.2001421.s013.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s014">
   <representation entry="aarx.2001421.s014.jpg" key="10.24196/journal.aarx.2001421.s014.jpg" mimetype="image/jpeg" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s015">
   <representation entry="aarx.2001421.s015.xlsx" key="10.24196/journal.aarx.2001421.s015.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s016">
   <representation entry="aarx.2001421.s016.tif" key="10.24196/journal.aarx.2001421.s016.tif" mimetype="image/tiff" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s017">
   <representation entry="aarx.2001421.s017.xlsx" key="10.24196/journal.aarx.2001421.s017.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s018">
   <representation entry="aarx.2001421.s018.tif" key="10.24196/journal.aarx.2001421.s018.tif" mimetype="image/tiff" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s019">
   <representation entry="aarx.2001421.s019.xlsx" key="10.24196/journal.aarx.2001421.s019.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s020">
   <representation entry="aarx.2001421.s020.tif" key="10.24196/journal.aarx.2001421.s020.tif" mimetype="image/tiff" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s021">
   <representation entry="aarx.2001421.s021.xlsx" key="10.24196/journal.aarx.2001421.s021.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s022">
   <representation entry="aarx.2001421.s022.tif" key="10.24196/journal.aarx.2001421.s022.tif" mimetype="image/tiff" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s023">
   <representation entry="aarx.2001421.s023.xlsx" key="10.24196/journal.aarx.2001421.s023.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s024">
   <representation entry="aarx.2001421.s024.tif" key="10.24196/journal.aarx.2001421.s024.tif" mimetype="image/tiff" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s025">
   <representation entry="aarx.2001421.s025.xlsx" key="10.24196/journal.aarx.2001421.s025.xlsx" mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" type="supplementary"/>
  </object>
  <object type="supplementaryMaterial" uri="info:doi/10.24196/journal.aarx.2001421.s026">
   <representation entry="aarx.2001421.s026.tif" key="10.24196/journal.aarx.2001421.s026.tif" mimetype="image/tiff" type="supplementary"/>
  </object>
 </articleBundle>
 <ancillary>
  <file entry="manifest.xml" key="10.24196/journal.aarx.2001421.manifest.xml" mimetype="application/xml"/>
  <file entry="manifest.dtd" key="10.24196/journal.aarx.2001421.manifest.dtd" mimetype="application/xml-dtd"/>
  <file entry="aarx.2001421.xml.orig" key="10.24196/journal.aarx.2001421.xml.orig" mimetype="application/xml"/>
 </ancillary>
</manifest>

=== PLOS/rhino/test/data/manifest.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE manifest SYSTEM "/home/fcabrales/repo-plos/rhino/test/data/manifest.dtd">
<manifest>
 <articleBundle>
  <article uri="info:doi/10.1371/journal.pone.0170224">
   <representation entry="pone.0170224.xml" key="10.1371/journal.pone.0170224.XML" mimetype="application/xml" type="manuscript"/>
   <representation entry="pone.0170224.pdf" key="10.1371/journal.pone.0170224.pdf" mimetype="application/pdf" type="printable"/>
  </article>
  <object strkImage="True" type="standaloneStrikingImage" uri="info:doi/10.1371/journal.pone.0170224.strk">
   <representation entry="pone.0170224.strk.tif" key="10.1371/journal.pone.0170224.strk.tif" mimetype="image/tiff" type="original"/>
   <representation entry="pone.0170224.strk.PNG_M" key="10.1371/journal.pone.0170224.strk.PNG_M" mimetype="image/png" type="medium"/>
   <representation entry="pone.0170224.strk.PNG_L" key="10.1371/journal.pone.0170224.strk.PNG_L" mimetype="image/png" type="large"/>
   <representation entry="pone.0170224.strk.PNG_I" key="10.1371/journal.pone.0170224.strk.PNG_I" mimetype="image/png" type="inline"/>
   <representation entry="pone.0170224.strk.PNG_S" key="10.1371/journal.pone.0170224.strk.PNG_S" mimetype="image/png" type="small"/>
  </object>
  <object type="figure" uri="info:doi/10.1371/journal.pone.0170224.g001">
   <representation entry="pone.0170224.g001.tif" key="10.1371/journal.pone.0170224.g001.tif" mimetype="image/tiff" type="original"/>
   <representation entry="pone.0170224.g001.PNG_M" key="10.1371/journal.pone.0170224.g001.PNG_M" mimetype="image/png" type="medium"/>
   <representation entry="pone.0170224.g001.PNG_L" key="10.1371/journal.pone.0170224.g001.PNG_L" mimetype="image/png" type="large"/>
   <representation entry="pone.0170224.g001.PNG_I" key="10.1371/journal.pone.0170224.g001.PNG_I" mimetype="image/png" type="inline"/>
   <representation entry="pone.0170224.g001.PNG_S" key="10.1371/journal.pone.0170224.g001.PNG_S" mimetype="image/png" type="small"/>
  </object>
  <object type="figure" uri="info:doi/10.1371/journal.pone.0170224.g002">
   <representation entry="pone.0170224.g002.tif" key="10.1371/journal.pone.0170224.g002.tif" mimetype="image/tiff" type="original"/>
   <representation entry="pone.0170224.g002.PNG_M" key="10.1371/journal.pone.0170224.g002.PNG_M" mimetype="image/png" type="medium"/>
   <representation entry="pone.0170224.g002.PNG_L" key="10.1371/journal.pone.0170224.g002.PNG_L" mimetype="image/png" type="large"/>
   <representation entry="pone.0170224.g002.PNG_I" key="10.1371/journal.pone.0170224.g002.PNG_I" mimetype="image/png" type="inline"/>
   <representation entry="pone.0170224.g002.PNG_S" key="10.1371/journal.pone.0170224.g002.PNG_S" mimetype="image/png" type="small"/>
  </object>
  <object type="figure" uri="info:doi/10.1371/journal.pone.0170224.g003">
   <representation entry="pone.0170224.g003.tif" key="10.1371/journal.pone.0170224.g003.tif" mimetype="image/tiff" type="original"/>
   <representation entry="pone.0170224.g003.PNG_M" key="10.1371/journal.pone.0170224.g003.PNG_M" mimetype="image/png" type="medium"/>
   <representation entry="pone.0170224.g003.PNG_L" key="10.1371/journal.pone.0170224.g003.PNG_L" mimetype="image/png" type="large"/>
   <representation entry="pone.0170224.g003.PNG_I" key="10.1371/journal.pone.0170224.g003.PNG_I" mimetype="image/png" type="inline"/>
   <representation entry="pone.0170224.g003.PNG_S" key="10.1371/journal.pone.0170224.g003.PNG_S" mimetype="image/png" type="small"/>
  </object>
  <object type="figure" uri="info:doi/10.1371/journal.pone.0170224.g004">
   <representation entry="pone.0170224.g004.tif" key="10.1371/journal.pone.0170224.g004.tif" mimetype="image/tiff" type="original"/>
   <representation entry="pone.0170224.g004.PNG_M" key="10.1371/journal.pone.0170224.g004.PNG_M" mimetype="image/png" type="medium"/>
   <representation entry="pone.0170224.g004.PNG_L" key="10.1371/journal.pone.0170224.g004.PNG_L" mimetype="image/png" type="large"/>
   <representation entry="pone.0170224.g004.PNG_I" key="10.1371/journal.pone.0170224.g004.PNG_I" mimetype="image/png" type="inline"/>
   <representation entry="pone.0170224.g004.PNG_S" key="10.1371/journal.pone.0170224.g004.PNG_S" mimetype="image/png" type="small"/>
  </object>
 </articleBundle>
 <ancillary>
  <file entry="manifest.xml" key="10.1371/journal.pone.0170224.manifest.xml" mimetype="application/xml"/>
  <file entry="manifest.dtd" key="10.1371/journal.pone.0170224.manifest.dtd" mimetype="application/xml-dtd"/>
  <file entry="pone.0170224.xml.orig" key="10.1371/journal.pone.0170224.xml.orig" mimetype="application/xml"/>
 </ancillary>
</manifest>
